#!/usr/bin/env Rscript

# module_documentation.r
# Documentation generation module for the SDOH pipeline

# Load required packages
library(dplyr)
library(readr)
library(knitr)

#' Generate documentation for the SDOH dataset
#'
#' This function generates comprehensive documentation for the SDOH dataset,
#' including updating the data dictionary, README files, and other documentation.
#'
#' @param crosswalk The variable crosswalk dataframe
#' @param output_dir Directory where documentation will be stored
#' @return TRUE if successful, FALSE otherwise
generate_documentation <- function(crosswalk,
                                 output_dir = "docs") {
  
  log_message("\nSTEP 7: GENERATING DOCUMENTATION",
             level = "INFO", show_console = TRUE)
  
  # Create output directory if it doesn't exist
  if (!dir.exists(output_dir)) {
    dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
  }
  
  # Generate main data dictionary
  generate_data_dictionary(crosswalk, file.path(output_dir, "DATA_DICTIONARY.md"))
  
  # Update README files with correct variable counts
  update_readmes(crosswalk)
  
  # Generate domain-specific documentation
  generate_domain_documentation(crosswalk, output_dir)
  
  log_message("Documentation generation complete", 
             level = "INFO", show_console = TRUE)
  
  return(TRUE)
}

#' Generate the main data dictionary
#'
#' Creates a comprehensive data dictionary with all variables
#' 
#' @param crosswalk The variable crosswalk dataframe
#' @param output_file Path to write the data dictionary
#' @return TRUE if successful
generate_data_dictionary <- function(crosswalk, output_file) {
  log_message("Generating data dictionary...", 
             level = "INFO", show_console = TRUE)
  
  # Count variables by domain
  domain_counts <- crosswalk %>%
    group_by(domain) %>%
    summarise(count = n()) %>%
    arrange(desc(count))
  
  # Total variable count
  total_count <- nrow(crosswalk)
  
  # Sort variables by domain and name
  sorted_vars <- crosswalk %>%
    arrange(domain, variable_name)
  
  # Create a markdown table for each domain
  domain_tables <- list()
  for (d in unique(sorted_vars$domain)) {
    domain_vars <- sorted_vars %>% filter(domain == d)
    
    domain_table <- "| Variable Name | Description | Type | Years Available | Source |\n"
    domain_table <- paste0(domain_table, "|-------------|-------------|------|----------------|--------|\n")
    
    for (i in 1:nrow(domain_vars)) {
      var <- domain_vars[i, ]
      
      # Format years available
      years <- paste(var$min_year, "-", var$max_year)
      
      # Add row
      domain_table <- paste0(domain_table, 
                           "| `", var$variable_name, "` | ", 
                           var$description, " | ",
                           var$type, " | ",
                           years, " | ",
                           var$source, " |\n")
    }
    
    domain_tables[[d]] <- domain_table
  }
  
  # Create the full markdown content
  content <- paste0("# US County Social Determinants of Health Data Dictionary\n\n")
  content <- paste0(content, "This dataset contains ", total_count, " county-level variables across multiple domains related to social determinants of health.\n\n")
  
  # Add summary table
  content <- paste0(content, "## Summary of Variables by Domain\n\n")
  content <- paste0(content, "| Domain | Number of Variables |\n")
  content <- paste0(content, "|--------|---------------------|\n")
  
  for (i in 1:nrow(domain_counts)) {
    content <- paste0(content, "| ", domain_counts$domain[i], " | ", domain_counts$count[i], " |\n")
  }
  
  content <- paste0(content, "| **Total** | **", total_count, "** |\n\n")
  
  # Add each domain's variable table
  content <- paste0(content, "## Variables by Domain\n\n")
  
  for (d in names(domain_tables)) {
    content <- paste0(content, "### ", d, "\n\n")
    content <- paste0(content, domain_tables[[d]], "\n\n")
  }
  
  # Add footer
  content <- paste0(content, "## Notes\n\n")
  content <- paste0(content, "- Data availability varies by county and year\n")
  content <- paste0(content, "- Variable types include: numeric_count, numeric_percent, numeric_rate, numeric_index, numeric_money, numeric_years\n")
  content <- paste0(content, "- This dictionary was automatically generated by the SDOH pipeline\n")
  content <- paste0(content, "- Last updated: ", format(Sys.Date(), "%B %d, %Y"), "\n")
  
  # Write to file
  writeLines(content, output_file)
  
  log_message(paste("Data dictionary written to", output_file), 
             level = "INFO", show_console = TRUE)
  
  return(TRUE)
}

#' Update README files with correct variable counts
#'
#' @param crosswalk The variable crosswalk dataframe
#' @return TRUE if successful
update_readmes <- function(crosswalk) {
  log_message("Updating README files...", 
             level = "INFO", show_console = TRUE)
  
  # Use the crosswalk module's function to update documentation
  source("consolidate_crosswalks.r")
  update_variable_documentation(crosswalk)
  
  return(TRUE)
}

#' Generate domain-specific documentation
#' 
#' @param crosswalk The variable crosswalk dataframe
#' @param output_dir Directory to store domain documentation
#' @return TRUE if successful
generate_domain_documentation <- function(crosswalk, output_dir) {
  # Create data_sources directory if it doesn't exist
  data_sources_dir <- file.path(output_dir, "data_sources")
  if (!dir.exists(data_sources_dir)) {
    dir.create(data_sources_dir, recursive = TRUE, showWarnings = FALSE)
  }
  
  # Some key domains that need detailed documentation
  key_domains <- c(
    "Traffic Safety",
    "Health Outcomes",
    "Environmental",
    "Food Environment & Access"
  )
  
  for (domain in key_domains) {
    domain_vars <- crosswalk %>% filter(domain == domain)
    if (nrow(domain_vars) > 0) {
      # Create domain file name (replace spaces and special chars)
      file_name <- gsub(" ", "_", toupper(domain))
      file_name <- gsub("&|\\+", "AND", file_name)
      file_path <- file.path(data_sources_dir, paste0(file_name, "_DATA.md"))
      
      # Skip if the file already exists
      if (file.exists(file_path)) {
        next
      }
      
      # Create domain documentation
      content <- paste0("# ", domain, " Data\n\n")
      content <- paste0(content, "This document provides details about the ", domain, " variables in the SDOH dataset.\n\n")
      
      # Add variables table
      content <- paste0(content, "## Variables\n\n")
      content <- paste0(content, "| Variable Name | Description | Type | Years Available | Source |\n")
      content <- paste0(content, "|-------------|-------------|------|----------------|--------|\n")
      
      for (i in 1:nrow(domain_vars)) {
        var <- domain_vars[i, ]
        
        # Format years available
        years <- paste(var$min_year, "-", var$max_year)
        
        # Add row
        content <- paste0(content, 
                         "| `", var$variable_name, "` | ", 
                         var$description, " | ",
                         var$type, " | ",
                         years, " | ",
                         var$source, " |\n")
      }
      
      # Add domain-specific notes
      content <- paste0(content, "\n## Data Sources\n\n")
      
      # Add generic source information based on domain
      if (domain == "Traffic Safety") {
        content <- paste0(content, "These variables come from the National Highway Traffic Safety Administration's Fatality Analysis Reporting System (FARS), which provides data on all fatal injuries in motor vehicle traffic crashes.\n\n")
        content <- paste0(content, "- **Source Website**: https://www.nhtsa.gov/research-data/fatality-analysis-reporting-system-fars\n")
        content <- paste0(content, "- **Years Available**: 1975-present\n")
      } else if (domain == "Health Outcomes") {
        content <- paste0(content, "Health outcomes data comes from multiple sources including CDC PLACES, CDC WONDER, and the Institute for Health Metrics and Evaluation (IHME).\n\n")
        content <- paste0(content, "- **CDC PLACES**: https://www.cdc.gov/places/\n")
        content <- paste0(content, "- **CDC WONDER**: https://wonder.cdc.gov/\n")
        content <- paste0(content, "- **IHME**: http://www.healthdata.org/\n")
      }
      
      # Write to file
      writeLines(content, file_path)
      log_message(paste("Generated documentation for", domain, "variables at", file_path), 
                 level = "INFO", show_console = TRUE)
    }
  }
  
  return(TRUE)
}

# Only run if executed directly (not sourced)
if (!exists("is_sourced") || !is_sourced()) {
  message("Documentation module cannot be run directly. Use the unified pipeline.")
}